name: Build and Push Docker Images
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pabvlov:latest

      - name: Deploy to production
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        working-directory: ./
        run: |
           echo "$SSH_KEY" > /tmp/deploy_key
            chmod 600 /tmp/deploy_key
            ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST '
              docker-compose pull
              docker-compose down
              docker-compose up -d
            '